import { Car, SiteSettings } from './types';

export const DEFAULT_SETTINGS: SiteSettings = {
  "phone": "082321241633",
  "whatsapp": "6282321241633",
  "waMessageTemplate": "Halo Kerabat Rentcar Jambi, saya ingin menanyakan dan menyewa mobil {mobil}. Mohon info ketersediaannya.",
  "companyName": "PT. KERABAT BERSINAR ABADI",
  "brandName": "Kerabat Rentcar",
  "address": "Kota Jambi, Provinsi Jambi, Indonesia",
  "hours": "24 Jam Setiap Hari (Senin - Minggu)",
  "instagram": "https://instagram.com",
  "tiktok": "https://tiktok.com",
  "facebook": "https://facebook.com",
  "googleMapsEmbed": "https://www.google.com/maps/embed?pb=!4v1789161223024!6m8!1m7!1sumfp3f-hL-nNjHLrH3uvgg!2m2!1d-6.168920047468529!2d106.7613222165844!3f330.22577!4f0!5f0.7820865974627469",
  "bannerCtaTitle": "Bersiaplah untuk pengalaman sewa mobil terbaik di Kota Jambi!",
  "bannerCtaButton": "Hubungi Kami : 082321241633",
  "heroImage": "/hero.webp",
  "fleetHeroImage": "/hero-fleet.webp",
  "bannerPenutupImage": "/banner-penutup.webp",
  "adminUsername": "admin123",
  "adminPassword": "admin123"
};

export const DEFAULT_CARS: Car[] = [
  {
    "id": "car-1",
    "name": "Toyota Avanza Facelift",
    "image": "/cars/Avanza_fc_350rb.webp",
    "category": "MPV",
    "price12h": "Rp 350.000",
    "priceDaily": "Rp 500.000 - Rp 650.000",
    "priceMonthly": "Rp 7.500.000",
    "seats": 7,
    "transmission": "Matic & Manual",
    "luggage": "",
    "status": "available",
    "featured": true,
    "notes": "Mobil keluarga terfavorit, lincah, irit, dan nyaman untuk perjalanan dinas maupun keluarga."
  },
  {
    "id": "car-2",
    "name": "Honda Brio",
    "image": "/cars/Brio_350rb.webp",
    "category": "City Car",
    "price12h": "Rp 350.000",
    "priceDaily": "Rp 500.000 - Rp 600.000",
    "priceMonthly": "Rp 7.000.000",
    "seats": 5,
    "transmission": "Matic",
    "luggage": "",
    "status": "available",
    "featured": true,
    "notes": "City car lincah, gesit, hemat bensin, sangat praktis untuk mobilitas di perkotaan."
  },
  {
    "id": "car-3",
    "name": "Honda Brio RS Full Modif",
    "image": "/cars/Brio_RS_full_modif_400rb.webp",
    "category": "City Car",
    "price12h": "Rp 400.000",
    "priceDaily": "Rp 550.000 - Rp 650.000",
    "priceMonthly": "Rp 7.500.000",
    "seats": 5,
    "transmission": "Matic",
    "luggage": "",
    "status": "available",
    "featured": false,
    "notes": "Tampil sporty dan elegan dengan sentuhan modifikasi keren, cocok untuk anak muda dan photoshoot."
  },
  {
    "id": "car-4",
    "name": "Honda BR-V",
    "image": "/cars/BRV_400rb.webp",
    "category": "SUV",
    "price12h": "Rp 400.000",
    "priceDaily": "Rp 550.000 - Rp 700.000",
    "priceMonthly": "Rp 8.000.000",
    "seats": 7,
    "transmission": "Matic",
    "luggage": "",
    "status": "available",
    "featured": true,
    "notes": "SUV tangguh dengan ground clearance tinggi, interior lapang, siap melibas segala rute."
  },
  {
    "id": "car-5",
    "name": "Honda City Hatchback",
    "image": "/cars/City_hatchback_500rb.webp",
    "category": "City Car",
    "price12h": "Rp 500.000",
    "priceDaily": "Rp 650.000 - Rp 800.000",
    "priceMonthly": "Rp 9.000.000",
    "seats": 5,
    "transmission": "Matic",
    "luggage": "",
    "status": "available",
    "featured": false,
    "notes": "Hatchback premium berdesain agresif, kabin hening dan fitur canggih untuk perjalanan berkelas."
  },
  {
    "id": "car-6",
    "name": "Toyota Fortuner GR Sport",
    "image": "/cars/Fortuner_GR_1_2jt.webp",
    "category": "SUV",
    "price12h": "Rp 1.200.000",
    "priceDaily": "Rp 1.500.000 - Rp 1.800.000",
    "priceMonthly": "Rp 23.000.000",
    "seats": 7,
    "transmission": "Matic",
    "luggage": "",
    "status": "available",
    "featured": true,
    "notes": "Gagah, prestisius, bertenaga besar, sempurna untuk tamu penting VVIP dan perjalanan dinas executive."
  },
  {
    "id": "car-7",
    "name": "Mitsubishi Pajero Sport Dakar 4x2",
    "image": "/cars/Pajero_Dakar_4x2_1_2jt.webp",
    "category": "SUV",
    "price12h": "Rp 1.200.000",
    "priceDaily": "Rp 1.500.000 - Rp 1.800.000",
    "priceMonthly": "Rp 23.000.000",
    "seats": 7,
    "transmission": "Matic",
    "luggage": "",
    "status": "available",
    "featured": true,
    "notes": "SUV mewah berperforma buas dengan sunroof, suspensi sangat stabil dan interior eksklusif."
  },
  {
    "id": "car-8",
    "name": "Toyota Innova Reborn 2.4 G AT",
    "image": "/cars/Reborn_2_4_g_at_600rb.webp",
    "category": "MPV",
    "price12h": "Rp 600.000",
    "priceDaily": "Rp 750.000 - Rp 900.000",
    "priceMonthly": "Rp 10.500.000",
    "seats": 7,
    "transmission": "Matic",
    "luggage": "",
    "status": "available",
    "featured": true,
    "notes": "Mesin diesel bertenaga, transmisi matic halus dan kabin sangat senyap untuk kenyamanan maksimal."
  },
  {
    "id": "car-9",
    "name": "Toyota Innova Reborn 2.4 G MT",
    "image": "/cars/Reborn_2_4_G_mt_600rb.webp",
    "category": "MPV",
    "price12h": "Rp 600.000",
    "priceDaily": "Rp 700.000 - Rp 850.000",
    "priceMonthly": "Rp 10.000.000",
    "seats": 7,
    "transmission": "Manual",
    "luggage": "",
    "status": "available",
    "featured": false,
    "notes": "Innova diesel manual responsif, tangguh di tanjakan, pilihan favorit perjalanan luar kota."
  },
  {
    "id": "car-10",
    "name": "Daihatsu Terios",
    "image": "/cars/Terios_400rb.webp",
    "category": "SUV",
    "price12h": "Rp 400.000",
    "priceDaily": "Rp 550.000 - Rp 650.000",
    "priceMonthly": "Rp 7.500.000",
    "seats": 7,
    "transmission": "Matic & Manual",
    "luggage": "",
    "status": "available",
    "featured": false,
    "notes": "Compact SUV 7-seater lincah dan hemat bahan bakar, cocok untuk keluarga dan medan berbukit."
  },
  {
    "id": "car-11",
    "name": "Daihatsu Xenia R ADS",
    "image": "/cars/Xenia_R_ADS_400rb.webp",
    "category": "MPV",
    "price12h": "Rp 400.000",
    "priceDaily": "Rp 550.000 - Rp 650.000",
    "priceMonthly": "Rp 7.500.000",
    "seats": 7,
    "transmission": "Matic & Manual",
    "luggage": "",
    "status": "available",
    "featured": false,
    "notes": "Tampilan sporty ADS dengan kabin sofa mode yang fleksibel, sangat nyaman untuk liburan keluarga."
  }
];
